/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2016-06-10 06:40:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>B I T</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container clearfix\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-8 col-sm-12\">\r\n");
      out.write("                <div class=\"qsz-orange\">\r\n");
      out.write("                    <div class=\"qsz-title-orange font-16 en\">\r\n");
      out.write("                        <a href=\"http://quasarzone.co.kr/bbs/board.php?bo_table=qc_qsz\">\r\n");
      out.write("                            <span class=\"pull-right lightgray\">+</span>\r\n");
      out.write("                            <b class=\"lightgray\">BIT 공식칼럼 \r\n");
      out.write("                            </b>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("<div class=\"widget-box\">\r\n");
      out.write("<div class=\"img-wrap col-lg-12\" style=\"padding-bottom:42.4%;\">\r\n");
      out.write("\t<div class=\"img-item\">\r\n");
      out.write("\t\t<div id=\"htrcpilfoskmenjuqgdv\" class=\"flexslider\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("                 <!--    <div class=\"col-md-6\" style=\"display:none;\">\r\n");
      out.write("                        <style>\r\n");
      out.write("\t#foixmthurewlsqcdvgnyjkp { margin-right:-10px; margin-bottom:-10px; }\r\n");
      out.write("\t#foixmthurewlsqcdvgnyjkp .post-row { width:100%; }\r\n");
      out.write("\t#foixmthurewlsqcdvgnyjkp .post-list { margin-right:10px; margin-bottom:10px; }\r\n");
      out.write("\t#foixmthurewlsqcdvgnyjkp .post-subject { height:20px; }\r\n");
      out.write("\t#foixmthurewlsqcdvgnyjkp .img-wrap { padding-bottom:75%; }\r\n");
      out.write("\t</style>\r\n");
      out.write("<div id=\"foixmthurewlsqcdvgnyjkp\" class=\"basic-post-gallerym\">\r\n");
      out.write("\t\t<div class=\"post-row\">\r\n");
      out.write("\t\t<div class=\"post-list\">\r\n");
      out.write("\t\t\t<div class=\"post-image\">\r\n");
      out.write("\t\t\t\t<a href=\"http://quasarzone.co.kr/bbs/board.php?bo_table=qc_qsz&amp;wr_id=4885\" class=\"ellipsis\">\r\n");
      out.write("\t\t\t\t\t<div class=\"img-wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"img-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"http://quasarzone.co.kr/data/file/qc_qsz/thumb-2949820706_LxFAbTG8_e0440708c424694164a2e13b91198d817bcbcb85_400x300.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"post-content\">\r\n");
      out.write("\t\t\t\t<div class=\"post-subject\">\r\n");
      out.write("\t\t\t\t\t<a href=\"http://quasarzone.co.kr/bbs/board.php?bo_table=qc_qsz&amp;wr_id=4885\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<b>BRAVOTEC 트레저 X6 630T 타이탄 글래스 화이트 케이스</b>\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"post-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t﻿화려함과 실용성, 그 사이의 균형을 타이탄 글래스로 BRAVOTEC이 새롭게 정의하다BRAVOTEC 트레저 X6 630T 타이탄 글래스 화이트…\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"post-text post-ko txt-short ellipsis\">\r\n");
      out.write("\t\t\t\t\t<span style=\"color:#F90;\">퀘이사존자석씌</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"post-sp\">|</span>\r\n");
      out.write("\t\t\t\t\t\t케이스\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"post-sp\">|</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"txt-normal\">\r\n");
      out.write("\t\t\t\t\t\t\t06.07\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"post-sp\">|</span><span class=\"count orange\">&nbsp;<i class=\"fa fa-commenting\"></i>&nbsp;211</span><span class=\"post-sp\">|</span>\r\n");
      out.write("\t\t\t\t\t                        <span class=\"count orange\">&nbsp;<i class=\"fa fa-thumbs-o-up\"></i>&nbsp;46</span>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"clearfix\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-6\" style=\"display:none;\">\r\n");
      out.write("                        <style>\r\n");
      out.write("\t#qfgvjnxtikprwsolhmu .post-image { width:151px; height:136px; }\r\n");
      out.write("\t#qfgvjnxtikprwsolhmu .post-subject { height:120px; }\r\n");
      out.write("\t#qfgvjnxtikprwsolhmu .img-wrap { padding-bottom:90%; }\r\n");
      out.write("</style>\r\n");
      out.write("<div id=\"qfgvjnxtikprwsolhmu\" class=\"basic-post-mix2\">\r\n");
      out.write("\t<div class=\"post-wrap\">\r\n");
      out.write("\t\t\t<div class=\"media post-list\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"pull-left post-image\">\r\n");
      out.write("\t\t\t\t\t<a href=\"http://quasarzone.co.kr/bbs/board.php?bo_table=qc_qsz&amp;wr_id=4885\" class=\"ellipsis\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"img-wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"img-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"http://quasarzone.co.kr/data/file/qc_qsz/thumb-2949820706_LxFAbTG8_e0440708c424694164a2e13b91198d817bcbcb85_150x135.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"media-body\">\r\n");
      out.write("\t\t\t\t<div class=\"post-content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"post-subject\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://quasarzone.co.kr/bbs/board.php?bo_table=qc_qsz&amp;wr_id=4885\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<b>BRAVOTEC 트레저 X6 630T 타이탄 글래스 화이트 케이스</b>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"post-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t﻿화려함과 실용성, 그 사이의 균형을 타이탄 글래스로 BRAVOTEC이 새롭게 정의하다BRAVOTEC 트레저 X6 630T 타이탄 글래스 화이트 케이스케이스 분석 칼럼 | 퀘이사존자석씌화려함과 실용성을 둘다 잡기에는…\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"post-text post-ko txt-short ellipsis\">\r\n");
      out.write("\t\t\t\t\t\t<span style=\"color:#F90;\">퀘이사존자석씌</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"post-sp\">|</span>\r\n");
      out.write("\t\t\t\t\t\t\t케이스\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"post-sp\">|</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"txt-normal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t06.07\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"count orangered\">+211</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"media post-list\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"pull-left post-image\">\r\n");
      out.write("\t\t\t\t\t<a href=\"http://quasarzone.co.kr/bbs/board.php?bo_table=qc_qsz&amp;wr_id=4287\" class=\"ellipsis\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"img-wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"img-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"http://quasarzone.co.kr/data/file/qc_qsz/thumb-1037838157_Iln8WeUt_c79147e34a1273197b24c4d738110b005771d938_150x135.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"media-body\">\r\n");
      out.write("\t\t\t\t<div class=\"post-content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"post-subject\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://quasarzone.co.kr/bbs/board.php?bo_table=qc_qsz&amp;wr_id=4287\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<b>인텔 Core i7-6950X & MSI X99A GAMING PRO CARBON</b>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"post-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t인텔은 2008년 말, 그동안 사용하던 LGA775 소켓을 버리고새로운 소켓을 2종류 발표하였다. LGA1156으로 이후 LGA115x시리즈로 불리는 퍼포먼스급과 LGA1366의 하이엔드급 소켓이다. LGA1156이…\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"post-text post-ko txt-short ellipsis\">\r\n");
      out.write("\t\t\t\t\t\t<span style=\"color:#F90;\">퀘이사존센스</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"post-sp\">|</span>\r\n");
      out.write("\t\t\t\t\t\t\tCPU\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"post-sp\">|</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"txt-normal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t05.31\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"count orangered\">+144</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-4 hidden-sm hidden-xs\">\r\n");
      out.write("                                    로그인 시작\r\n");
      out.write("                    <div class=\"qsz-gray\">\r\n");
      out.write("                        <div class=\"div-title-underbar font-16 en\">\r\n");
      out.write("                            <b>로그인</b>                        </div>\r\n");
      out.write("                        <div class=\"widget-box\">\r\n");
      out.write("                                <div class=\"widget-simple-outlogin\">\r\n");
      out.write("        \r\n");
      out.write("                <form id=\"simple_outlogin\" name=\"simple_outlogin\" method=\"post\" action=\"http://quasarzone.co.kr/bbs/login_check.php\" autocomplete=\"off\" role=\"form\" class=\"form\" onsubmit=\"return simple_outlogin_form(this);\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"url\" value=\"%2F\">\r\n");
      out.write("                    <div class=\"login-box\">\r\n");
      out.write("                        <div class=\"login-cell\">\r\n");
      out.write("                            <input type=\"text\" name=\"mb_id\" id=\"mb_id\" class=\"form-control input-sm\" required placeholder=\"아이디\" tabindex=\"21\" onKeyDown=\"simple_outlogin_onKeyDown();\">\r\n");
      out.write("                            <input type=\"password\" name=\"mb_password\" id=\"mb_password\" class=\"form-control input-sm no-top-border\" required placeholder=\"비밀번호\" tabindex=\"22\" onKeyDown=\"simple_outlogin_onKeyDown();\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"login-cell login-btn\" tabindex=\"23\" onclick=\"simple_outlogin_submit();\" onKeyDown=\"simple_outlogin_onKeyDown();\">\r\n");
      out.write("                            로그인\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"login-misc font-12 text-muted ellipsis\">\r\n");
      out.write("                        <div class=\"pull-left\">\r\n");
      out.write("                            <label>\r\n");
      out.write("                                <input type=\"checkbox\" name=\"auto_login\" value=\"1\" id=\"remember_me\" class=\"remember-me\"> 자동로그인</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"pull-right text-muted\">\r\n");
      out.write("                            <a href=\"http://quasarzone.co.kr/bbs/register.php\"><span class=\"text-muted\">회원가입</span></a>\r\n");
      out.write("                            <span class=\"bar\">|</span>\r\n");
      out.write("                            <a href=\"http://quasarzone.co.kr/bbs/password_lost.php\" class=\"win_password_lost\"><span class=\"text-muted\">비밀번호찾기</span></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"clearfix\"></div>\r\n");
      out.write("                                   <div class=\"h10\"></div>\r\n");
      out.write("                                회원 정보\r\n");
      out.write("                                <div class=\"qsz-ui\" id=\"qsz-ui\">\r\n");
      out.write("                                    <iframe class=\"qsz-frame\" src=\"http://quasarzone.co.kr/bbs/banner.php\" id=\"contentFrame\" name=\"contentFrame\" scrolling=\"auto\" frameborder=\"0\" marginheight=\"0\" marginwidth=\"0\" height=\"210px\" width=\"100%\"></iframe>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                회원 정보                    \r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("                <script>\r\n");
      out.write("                    function simple_outlogin_form(f) {\r\n");
      out.write("                        if (f.mb_id.value == '') {\r\n");
      out.write("                            alert('아이디를 입력해 주세요.');\r\n");
      out.write("                            f.mb_id.focus();\r\n");
      out.write("                            return false;\r\n");
      out.write("                        }\r\n");
      out.write("                        if (f.mb_password.value == '') {\r\n");
      out.write("                            alert('비밀번호를 입력해 주세요.');\r\n");
      out.write("                            f.mb_password.focus();\r\n");
      out.write("                            return false;\r\n");
      out.write("                        }\r\n");
      out.write("                        return true;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    function simple_outlogin_submit() {\r\n");
      out.write("                        var f = document.getElementById(\"simple_outlogin\");\r\n");
      out.write("                        if (simple_outlogin_form(f)) {\r\n");
      out.write("                            $(\"#simple_outlogin\").submit();\r\n");
      out.write("                        }\r\n");
      out.write("                        return false;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    function simple_outlogin_onKeyDown() {\r\n");
      out.write("                        if (event.keyCode == 13) {\r\n");
      out.write("                            simple_outlogin_submit();\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                </script>\r\n");
      out.write("                    </div>                        </div>\r\n");
      out.write("             로그인 끝 -->        </div>       \r\n");
      out.write("            \r\n");
      out.write("                                </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
